### ISSUE TITLE
Using JSDoc as 

### ISSUE THREAD

**Issue by AienTech** [nainemom/framevuerk#1]
Hi,

did you considered using JSDoc to document using annotation?
I think I could be a good idea to use that... I couldn't find it in `package.json`

**Comment by nainemom** [comment]
hi. as my knowledge about JSDoc, it generate .html files inspired by .js files annotation. but i think it's better idea to creating more powerful document pages along with examples and also styles description. for now, i trying to create new simple application (inside ./doc directory) uses current library, to explain what this library do.
